### ISSUE TITLE
Can I use it for compiling oneplus 7 with my device tree

### ISSUE THREAD

**Issue by midozalouk** [rabilgic/twrp_device_oneplus_hotdogb#1]
Hello sir
Thanks for your work i have tested in only my wife oneplus 7t and it works

Can i compile TWRP From your source using oneplus 7 device tree?

If not are there any tutorial you followed to make it work

I am stuck on bootloop on oxygen 12.i just need it to access internal storage or to reflash the oxygen official rom to be able to access the system

Thanks

**Comment by rabilgic** [comment]
> Hello sir Thanks for your work i have tested in only my wife oneplus 7t and it works
> 
> Can i compile TWRP From your source using oneplus 7 device tree?
> 
> If not are there any tutorial you followed to make it work
> 
> I am stuck on bootloop on oxygen 12.i just need it to access internal storage or to reflash the oxygen official rom to be able to access the system
> 
> Thanks

Hello,
Sorry for the late reply.
You can compile but there will be some lines and kernel you need to adapt to your device.
Use [zulip channel](https://twrp.zulipchat.com/) for your compilation questions.

**Comment by midozalouk** [comment]
Hello sir
Can you please guide me what i need to complete the job

All i need is to decrypt data to extract some data.

And I need invitation to zulip


Thanks sir

**Comment by midozalouk** [comment]
Hello sir 
i want your help 
i used your twrp with some modifications for my oneplus 7 
but i have a problem i can't mound the data partition to be able to decrypt it 

i have tried many ways with no succecess

where i should store the correct mount option in twrp.flags or fstab ?

i had another twrp package which can mount the data partition but don't include the decrypt package 

can i use their mount options ?

sorry if the question seems silly but i realy have no clue ?
